final_project/final_project/urls.py
from django.contrib import admin
from django.urls import path, include
from simple_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('simple_app/', include('simple_app.urls')),
]

final_project/simple_app/urls.py
from django.urls import path
from simple_app import views

app_name = 'simple_app'

urlpatterns = [
    path('register/', views.register, name='register')
]

final_project/simple_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)

    department = models.CharField(blank=False, max_length=50)
    profile_pic = models.ImageField(blank=True, upload_to='profile_pics')

    def __str__(self):
        return self.user.username

final_project/simple_app/forms.py
from django import forms
from django.contrib.auth.models import User
from simple_app.models import UserProfileInfo


class UserInfoForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'password', 'email')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('department', 'profile_pic')

final_project/simple_app/views.py
from django.shortcuts import render
from simple_app.forms import UserInfoForm, UserProfileInfoForm

# Create your views here.


def index(request):
    return render(request, 'simple_app/index.html')


def register(request):
    registered = False

    if(request.method == "POST"):
        user_info = UserInfoForm(data=request.POST)
        profile_info = UserProfileInfoForm(data=request.POST)

        if user_info.is_valid() and profile_info.is_valid():
            user = user_info.save()
            user.set_password(user.password)
            user.save()

            profile = profile_info.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print('One of the forms is not valid..Below are the error details:\n')
            print(user_info.errors, profile_info.errors)

    else:
        user_info = UserInfoForm()
        profile_info = UserProfileInfoForm()

    return render(request, 'simple_app/registration.html', {'registered': registered, 'user_form': user_info, 'profile_form': profile_info})

final_project/templates/simple_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <title>Final Project</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">AG</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'simple_app:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Log In/Log Out</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %} {% endblock %}
    </div>
  </body>
</html>

final_project/templates/simple_app/index.html
{% extends 'simple_app/base.html' %} {% block body_block %}
<h1 class="text-center">Welcome to AG Home Page</h1>
<h5 class="text-center">
  This is a simple project to demonstrate the functionality of Django project
</h5>
<p class="text-justify">
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque illum esse cum
  quidem nesciunt qui veniam ducimus nam a libero totam cupiditate ratione enim
  id, magnam iste harum deserunt beatae? Lorem ipsum dolor sit amet consectetur
  adipisicing elit. Inventore corrupti, laboriosam quidem, dolor cumque mollitia
  impedit nobis aperiam magnam rerum ducimus exercitationem ab pariatur error
  explicabo nihil, saepe vel incidunt. Lorem ipsum dolor sit amet consectetur
  adipisicing elit. Dignissimos modi cupiditate deserunt maxime sed similique
  natus! Eius vel error commodi molestias, facere obcaecati, veritatis cum
  similique iure sequi quibusdam voluptas? Lorem ipsum dolor sit amet
  consectetur adipisicing elit. Velit enim sequi consequuntur, possimus, eos
  commodi in debitis ducimus autem dolores vitae mollitia. Velit in placeat,
  dolore quasi omnis qui autem. Lorem ipsum dolor sit amet consectetur
  adipisicing elit. A perferendis velit aliquam? Hic voluptas quae error facilis
  quos ducimus numquam officiis, nisi esse dolorem asperiores qui cupiditate
  quisquam animi porro.
</p>
{% endblock%}

final_project/templates/simple_app/registration.html
{% extends 'simple_app/base.html' %} {% block body_block%}
<div class="container">
  <h1>Welcome to AG User Registration page.</h1>
  {% if registered %}
  <h1>Thank you for registering. Your details have been saved successfully.</h1>
  {% else %}
  <h1>Fill in the below form to create an account.</h1>
  <form method="POST" enctype="multipart/form-data" >
    <div class="form-group">
    {% csrf_token %} {{ user_form.as_p}} {{ profile_form.as_p}}
    <input type="submit" value="Register" class="btn btn-primary"/>
    </div>
  </form>
  {% endif %}
</div>
{% endblock%}